#!/usr/bin/env python3

import configparser
import datetime
import argparse
import os

config = configparser.ConfigParser()
config_file = os.path.join(os.environ['HOME'], '.slurmjobrc')
try:
    with open(config_file) as f:
        config.read_file(f)
except FileNotFoundError:
    print('Configuration file not found. Exiting now')
    exit()

parser = argparse.ArgumentParser()
parser.add_argument("-software", "-s", choices=['xtb','crest','gaussian','orca'], required=True)
parser.add_argument("-jobs", "-j", nargs='+', required=True, help='Input file for the requested program')
parser.add_argument("--input", required=False, help="Custom input file. Usually employed for XTB calculations")
parser.add_argument("--send-files", nargs='+', required=False, help="Send files from local dir to scratch dir")
parser.add_argument("-cores", "-c", type=int, required=True, help='Number of cores')
parser.add_argument("-mem", "-m", type=int, required=True, help='Memory in MB per core required')
parser.add_argument("-time", "-t", type=float, required=True, help='Maximum running time in hours')
parser.add_argument("-flags", nargs='+', default='', help='Flags for xtb or crest')
arguments = parser.parse_args()

duration = datetime.timedelta(hours=arguments.time)
totsec = duration.total_seconds()
h = totsec//3600
m = (totsec%3600) // 60
sec =(totsec%3600)%60 #just for reference
walltime = f"{int(h):02d}:{int(m):02d}:{int(sec):02d}"

def write_submission_script(*args):
    job_file = open(f"job_{JOB_BASENAME}.sh", mode='w')
    job_file.write('#!/bin/bash\n')

    # QUEUE SYSTEM SETTINGS
    if config['DEFAULT']['queue engine'] == 'slurm':
        QUEUE_JOB_ID = "$SLURM_JOB_ID"
        job_file.write(
            f'#SBATCH --job-name={JOB_BASENAME}\n'
            f'#SBATCH --output=job_%x_%A.log\n'
            '#SBATCH --nodes=1\n'
            f'#SBATCH --ntasks={arguments.cores}\n'
            '#SBATCH --cpus-per-task=1\n'
            f'#SBATCH --mem-per-cpu={arguments.mem}\n'
            f'#SBATCH --time={walltime}\n'
            f'#SBATCH --signal=B:TERM@60\n'
            '\n'
        )
    elif config['DEFAULT']['queue engine'] == 'PBS-Pro':
        QUEUE_JOB_ID = "$PBS_JOBID"
        job_file.write(
            f'#PBS -N {JOB_BASENAME}\n'
            f'#PBS -o {JOB_BASENAME}.stdout\n'
            f'#PBS -e {JOB_BASENAME}.stderr\n'
            f'#PBS -l select=1:ncpus={arguments.cores}:mem={arguments.cores*arguments.mem}mb\n'
            f'#PBS -l walltime={walltime}\n'
            '\n'
        )
    else:
        raise NotImplementedError(f"QUEUE System {config['DEFAULT']['queue engine']} is not implemented")

    # JOB SETTINGS
    JOB_SCRDIR = f"{config['DEFAULT']['scratch dir']}\"$USER\"/\"{QUEUE_JOB_ID}\""

    # DELETE SCRATCH DIR
    job_file.write("{:#^80}".format('   DELETE SCRATCH AND TEMP DATA   ')+'\n')
    job_file.write(
        'function clean_job() {\n'
        '  echo "Received SIG"\n'
        '  if [[ -d "$job_scratch_dir" ]]; then\n'
        '    echo "Copying outputs to local_dir"\n'
        '    cp -rv "$job_scratch_dir"/* "$job_local_dir"/\n'
        '    echo "Removing scratch dir"\n'
        '    rm -vrf "$job_scratch_dir"\n'
        '    echo "Job done"\n'
        '    echo ""\n'
        '  else\n'
        '    echo "scratch dir does not exist"\n'
        '    echo ""\n'
        '  fi\n'
        '  exit\n'
        '}\n'
        'trap clean_job EXIT HUP INT TERM ERR\n'
        '\n'
    )

    # JOB VARS
    job_file.write("{:#^80}".format('   JOB VARIABLES   ')+'\n')
    job_file.write(
        f'job_input="{JOB_BASENAME}.{JOB_INPUT_EXTENSION}"\n'
        f'job_submit_dir="{JOB_SUBMIT_DIR}"\n'
        '\n'
        f'job_local_dir=""$job_submit_dir"/{JOB_BASENAME}"\n'
        'mkdir -p $job_local_dir\n'
        '\n'
        f'job_scratch_dir="{JOB_SCRDIR}"\n'
        'mkdir -p $job_scratch_dir\n'
        '\n'
    )
    job_file.write(   
        #f'cp "$job_submit_dir"/"$job_input" "$job_local_dir"\n'
        f'cp "$job_submit_dir"/"$job_input" "$job_scratch_dir"\n'
        '\n'
    )
    # Custom inputs and external files
    if CUSTOM_INPUT:
        job_file.write(
            f'# REQUESTED: send custom input file to SCR_DIR\n'
            f'cp "$job_submit_dir"/{arguments.input} "$job_scratch_dir"\n'
            '\n'
        )
    if arguments.send_files:
        job_file.write(f'# REQUESTED: send additional files to SCR_DIR\n')
        for file in arguments.send_files:
            job_file.write(
                f'cp "$job_submit_dir"/{file} "$job_scratch_dir"\n'
            )
        job_file.write('\n')
    
    job_file.write(f'cd $job_scratch_dir\n')    
    job_file.write('\n')

    job_file.write(
        "{:#^80}".format('   JOB INFORMATION   ')+'\n'
        f'echo "Running job "$job_input""\n'
        f'echo "Job local dir "$job_local_dir""\n'
        f'echo "Job remote dir "$job_scratch_dir""\n'
        f'echo "Job ID "{QUEUE_JOB_ID}""\n'
        f'echo ""\n'
        '\n'
    )
    
    # SOFTWARE SETTINGS
    job_file.write("{:#^80}".format('   SOFTWARE SPECIFIC SETTINGS   ')+'\n')  
    write_software_specific_settings(job_file, JOB_SCRDIR, arguments.software, flags=JOB_FLAGS)

    job_file.write("{:#^80}".format('')+'\n')

    job_file.close()

def write_software_specific_settings(job_file, job_scrdir, software, flags=None):
    if software == 'orca':
        SOFTWARE_EXEDIR = f"\"{config['executables']['orca5']}\""
        SOFTWARE_SCRDIR = f'\""$job_scratch_dir"/scr\"'
        # ORCA SETTINGS
        job_file.write(
            f'export ORCA_EXEDIR={SOFTWARE_EXEDIR}\n'
            f'export ORCA_SCRDIR={SOFTWARE_SCRDIR}\n'
            f'mkdir $ORCA_SCRDIR\n'
            'export LD_LIBRARY_PATH="$ORCA_EXEDIR":"$LD_LIBRARY_PATH"\n'
            'export PATH="$PATH":"$ORCA_EXEDIR"\n'
            '\n'
        )
        # RUN JOB
        job_file.write(
            f'"$ORCA_EXEDIR"/orca "$job_scratch_dir"/"$job_input" > "$job_scratch_dir"/{JOB_BASENAME}.out\n'
            '\n'
        )
    elif software == 'gaussian':
        SOFTWARE_EXEDIR = f"\"{config['executables']['gaussian16']}\""
        SOFTWARE_SCRDIR = f'\""$job_scratch_dir"/gaussian_scratch\"'
        XTBHOME = f"\"{config['executables']['xtb']}\""
        NBO7_EXEDIR= f"\"{config['executables']['nbo7']}\""
        # GAUSSIAN16 SETTINGS
        job_file.write(
            f'export GAUSS_EXEDIR={SOFTWARE_EXEDIR}\n'
            'export PATH="$PATH":"$GAUSS_EXEDIR"\n'
            f'export NBO7_EXEDIR={NBO7_EXEDIR}\n'
            'export PATH="$PATH":"$NBO7_EXEDIR"\n'
            f'export GAUSS_SCRDIR={SOFTWARE_SCRDIR}\n'
            'mkdir $GAUSS_SCRDIR\n'
            '\n'
        )
        # XTB SETTINGS FOR GAUSSIAN-XTB INTERFACE
        job_file.write(
            f'export MKL_NUM_THREADS={arguments.cores}\n'
            f'export OMP_NUM_THREADS={arguments.cores}\n'
            f'export XTBHOME={XTBHOME}\n'
            'source "$XTBHOME"/share/xtb/config_env.bash\n'
            '\n'
        )
        # ADJUST GAUSSIAN CHECKPOINT OUTPUT FILE 
        job_file.write(
            f'sed -i \"s#%chk=#%chk=$job_scratch_dir/#g\" "$job_scratch_dir"/"$job_input"\n' 
            '\n'
        )
        # RUN JOB
        job_file.write(
            f'"$GAUSS_EXEDIR"/g16 < "$job_scratch_dir"/"$job_input" > "$job_scratch_dir"/{JOB_BASENAME}.log &\n'
            'wait\n'
            'exit \n'
            '\n'
        )   
    elif software == 'xtb':
        SOFTWARE_EXEDIR = f"\"{config['executables']['xtb']}\""
        SOFTWARE_SCRDIR = f"{job_scrdir}/scr"
        # XTB SETTINGS
        job_file.write(
            f'export MKL_NUM_THREADS={arguments.cores}\n'
            f'export OMP_NUM_THREADS={arguments.cores}\n'
            f'export XTBHOME={SOFTWARE_EXEDIR}\n'
            'source "$XTBHOME"/share/xtb/config_env.bash\n'
            '\n'
        )
        #RUN JOB
        job_file.write(
            f'"$XTBHOME"/bin/xtb "$job_scratch_dir"/"$job_input" {" ".join(flags)} &> "$job_scratch_dir"/xtb.output\n'
            '\n'
        )
    elif software == 'crest':
        XTBHOME=f"\"{config['executables']['xtb']}\""
        SOFTWARE_EXEDIR = f"\"{config['executables']['crest']}\""
        SOFTWARE_SCRDIR = f"{job_scrdir}/scr"
        # CREST SETTINGS
        job_file.write(
            f'export MKL_NUM_THREADS={arguments.cores}\n'
            f'export OMP_NUM_THREADS={arguments.cores}\n'
            f'export XTBHOME={XTBHOME}\n'
            'source "$XTBHOME"/share/xtb/config_env.bash\n'
            f'export CREST_EXEDIR={SOFTWARE_EXEDIR}'
            '\n'
        )
        #RUN JOB
        job_file.write(
            f'"$CREST_EXEDIR"/crest "$job_scratch_dir"/"$job_input" {" ".join(flags)} &> "$job_scratch_dir"/crest.output\n'
            '\n'
        )
    else:
        raise NotImplementedError(f"Software {software} is not implemented yet")

JOB_FLAGS = arguments.flags
if isinstance(arguments.flags, list) and arguments.input:
    CUSTOM_INPUT = os.path.basename(arguments.input)
    JOB_FLAGS.append(f"--input {CUSTOM_INPUT}")
else:
    CUSTOM_INPUT = False

for job in arguments.jobs:
    if os.path.isfile(job):
        JOB_BASENAME, JOB_INPUT_EXTENSION = job.split('.',1)
        JOB_SUBMIT_DIR = os.getcwd()
        JOB_LOCALDIR = os.path.join(JOB_SUBMIT_DIR, JOB_BASENAME)
        write_submission_script(job)
    else:
        raise OSError(f"Input file {job} not found")